export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/villas", label: "Villas" },
  { href: "/about-us", label: "About us" },
  { href: "/contact", label: "Contact " },
];

export const TOP_VILLAS = [
  {
    id: 1,
    price: 280,
    image: "/top-villas-1.svg",
    country: "Italy",
    view: "Mountains",
    title: "Villa Makarska",
    guests: 8,
    bedroom: 8,
    width: 460,
    bathroom: 4,
  },
  {
    id: 2,
    price: 110,
    image: "/top-villas-2.svg",
    country: "greece",
    view: "Seaside",
    title: "Villa Roxane",
    guests: 11,
    bedroom: 6,
    width: 120,
    bathroom: 25,
  },
  {
    id: 3,
    price: 240,
    image: "/top-villas-3.svg",
    country: "greece",
    view: "Seaside",
    title: "Aphrodite",
    guests: 12,
    bedroom: 6,
    width: 460,
    bathroom: 460,
  },
];
